require("ojas.plugins-setup")
require("ojas.core.options")
require("ojas.core.keymaps")
require("ojas.core.colorscheme")

require("ojas.plugins.comment")
require("ojas.plugins.nvim-tree")
require("ojas.plugins.lualine")
require("ojas.plugins.autopairs-config")
require("ojas.plugins.telescope")
require("ojas.plugins.nvim-cmp")
require("ojas.plugins.lsp.mason")
